// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkbB9nUicvfNIvZT7v8t7sKqhkZqtiFc',
    appId: '1:476070209878:web:d286be4b7c7207c5250ef7',
    messagingSenderId: '476070209878',
    projectId: 'smarthub-5a8fd',
    authDomain: 'smarthub-5a8fd.firebaseapp.com',
    storageBucket: 'smarthub-5a8fd.firebasestorage.app',
    measurementId: 'G-4VPG1CY2R0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2VwGGEIpZU1x0VVVVPxefxxmnz9dPlc',
    appId: '1:476070209878:ios:5e7cea9edc94094e250ef7',
    messagingSenderId: '476070209878',
    projectId: 'smarthub-5a8fd',
    storageBucket: 'smarthub-5a8fd.firebasestorage.app',
    iosBundleId: 'com.example.smartHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkbB9nUicvfNIvZT7v8t7sKqhkZqtiFc',
    appId: '1:476070209878:web:47a0697f6305c8b4250ef7',
    messagingSenderId: '476070209878',
    projectId: 'smarthub-5a8fd',
    authDomain: 'smarthub-5a8fd.firebaseapp.com',
    storageBucket: 'smarthub-5a8fd.firebasestorage.app',
    measurementId: 'G-QNHBDED0V6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2VwGGEIpZU1x0VVVVPxefxxmnz9dPlc',
    appId: '1:476070209878:ios:5e7cea9edc94094e250ef7',
    messagingSenderId: '476070209878',
    projectId: 'smarthub-5a8fd',
    storageBucket: 'smarthub-5a8fd.firebasestorage.app',
    iosBundleId: 'com.example.smartHub',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyHE1kNwnhPpKSZKrDQ6f5VGcYaoKAI8',
    appId: '1:476070209878:android:2168b301dfc48c24250ef7',
    messagingSenderId: '476070209878',
    projectId: 'smarthub-5a8fd',
    storageBucket: 'smarthub-5a8fd.firebasestorage.app',
  );

}